export const FETCH_INVENTARIO_DISPONIBLE = 'FETCH_INVENTARIO_DISPONIBLE';
export const SET_INVENTARIO_DISPONIBLE_SUCCES =
	'SET_INVENTARIO_DISPONIBLE_SUCCES';
export const SET_INVENTARIO_DISPONIBLE_FAIL = 'SET_INVENTARIO_DISPONIBLE_FAIL';
