export const FETCH_COMPRAS = 'FETCH_COMPRAS';
export const SET_COMPRAS_SUCESS = 'SET_COMPRAS_SUCESS';
export const SET_COMPRAS_FAIL = 'SET_COMPRAS_FAIL';
export const ID_COMPRA_SELECTED = 'ID_COMPRA_SELECTED';
