export const GET_OBJECT_TABLE = 'GET_OBJECT_TABLE';
export const CREATE_OBJECT_TABLE = 'CREATE_OBJECT_TABLE';
export const REMOVE_OBJECT_TABLE = 'REMOVE_OBJECT_TABLE';
export const FINISH_FACTURA_CLIENT = 'FINISH_FACTURA_CLIENT';
