export const FETCH_PRODUCTOS_LIST = 'FETCH_PRODUCTOS_LIST';
export const SET_PRODUCTOS_LIST_SUCCES = 'SET_PRODUCTOS_LIST_SUCCES';
export const SET_PRODUCTOS_LIST_FAIL = 'SET_PRODUCTOS_LIST_FAIL';
export const EDIT_PRODUCTOS_ITEM_STATUS = 'EDIT_PRODUCTOS_ITEM_STATUS';
export const EDIT_PRODUCTOS_ITEM_NOMBRE = 'EDIT_PRODUCTOS_ITEM_NOMBRE';
export const EDIT_PRODUCTOS_ITEM_DESCRIPCION =
	'EDIT_PRODUCTOS_ITEM_DESCRIPCION';
export const UPDATE_PRODUCTOS = 'UPDATE_PRODUCTOS';
export const UPDATE_PRODUCTOS_SUCCESS = 'UPDATE_PRODUCTOS_SUCCESS';
export const UPDATE_PRODUCTOS_FAIL = 'UPDATE_PRODUCTOS_FAIL';
export const CREATE_PRODUCTO = 'CREATE_PRODUCTO';
export const CREATE_PRODUCTO_SUCCESS = 'CREATE_PRODUCTO_SUCCESS';
export const CREATE_PRODUCTO_FAIL = 'CREATE_PRODUCTO_FAIL';
